baseURL = "https://haru067.com/blog"
publishDir = "../public/blog"
languageCode = "ja-jp"
title = "はるログ"
theme = "mochi"

[params]
dateformat = "2006-01-02"
avatar = "https://haru067.com/img/me.png"
home = "https://haru067.com/"
manifest = "https://haru067.com/blog/manifest.json"
adsense = "ca-pub-6607941391098256"

[[params.social]]
url = "https://github.com/haru067"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/haru067"
fa_icon = "fa-twitter"

[[params.favicon]]
url = "https://haru067.com/blog/favicon-32x32.png"
size = "32x32"

[[params.favicon]]
url = "https://haru067.com/blog/favicon-16x16.png"
size = "16x16"