baseURL = "https://haru067.com/blog"
publishDir = "../public/blog"
languageCode = "ja-jp"
title = "はるログ"
theme = "hemingway"

[params]

[[params.social]]
url = "https://github.com/haru067"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/haru067"
fa_icon = "fa-twitter"