# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Mochi"
license = "MIT"
licenselink = "https://github.com/haru067/hugo-mochi/blob/master/LICENSE.md"
description = "Really minimal blog theme for hugo"
homepage = "https://github.com/haru067/hugo-mochi"
tags = ["blog", "font awesome", "highlight.js"]
features = ["html5", "css3"]
min_version = 0.16

[author]
  name = "haru067"
  homepage = "http://haru067.com"
