name: CI

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      # with:
      #   submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        # extended: true

    - name: Build blog
      run: cd harulog && hugo --minify

    - name: Deploy to Firebase hosting
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
